USE [ProjekatSQL_Delfi]
GO

/****** Object:  Table [dbo].[Kupon]    Script Date: 2/21/2021 4:23:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Kupon](
	[KuponID] [int] IDENTITY(1,1) NOT NULL,
	[VrednostKupona] [float] NOT NULL,
	[DatumIstekaKupona] [date] NOT NULL,
 CONSTRAINT [PK_Kupon] PRIMARY KEY CLUSTERED 
(
	[KuponID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

